apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: whoami
resources:
- ../../../../../bases/whoami
components:
- ../../../../../components/ca-certs
patches:
- target:
    kind: HelmRelease
  path: whoami-patch.yaml
