apiVersion: operator.victoriametrics.com/v1beta1
kind: VMStaticScrape
metadata:
  name: blackbox-http
spec:
  jobName: blackbox-http
  targetEndpoints:
    - path: /probe
      targets:
        - https://git.0b.au
        - https://mealie.0b.au
        - https://karakeep.0b.au
        - https://immich.0b.au
        - https://coder.0b.au
        - https://paperless.0b.au
        - https://netbox.0b.au
        - https://outline.0b.au
        - https://harbor.0b.au
        - https://gotify.0b.au
        - https://auth.0b.au
      params:
        module: [http_2xx]
      relabelConfigs:
        - sourceLabels: [__address__]
          targetLabel: __param_target
        - sourceLabels: [__param_target]
          targetLabel: instance
        - targetLabel: __address__
          replacement: blackbox-exporter-prometheus-blackbox-exporter.monitoring.svc.cluster.local:9115
