---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: authelia
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./kubernetes/overlays/infrastructure/infra/applications/authelia
  dependsOn: 
    - name: repositories-infra
    - name: external-secrets-config
    - name: ingress-nginx
    - name: dragonfly-operator
    - name: cloudnative-pg
    - name: cert-manager
  healthChecks:
    - kind: HelmRelease
      name: authelia
      namespace: authelia
      apiVersion: helm.toolkit.fluxcd.io/v2beta1
  prune: true
  sourceRef:
    kind: "GitRepository"
    name: "flux-system"
