---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-config
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./kubernetes/overlays/infrastructure/infra/config
  dependsOn: 
    - name: cert-manager-config
    - name: cilium
    - name: external-dns-ipa
    - name: ingress-nginx
    - name: longhorn
    - name: repositories-infra
    - name: external-secrets-config
    - name: openshift-console
    - name: csi-driver-nfs
  prune: true
  sourceRef:
    kind: "GitRepository"
    name: "flux-system"
