---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: csi-driver-nfs
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./kubernetes/overlays/infrastructure/infra/applications/csi-driver-nfs
  dependsOn: 
    - name: repositories-infra
  healthChecks:
    - kind: HelmRelease
      name: csi-driver-nfs
      namespace: csi-driver-nfs
      apiVersion: helm.toolkit.fluxcd.io/v2beta1
  prune: true
  sourceRef:
    kind: "GitRepository"
    name: "flux-system"
