---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ddns
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./kubernetes/overlays/infrastructure/infra/applications/ddns
  prune: true
  sourceRef:
    kind: "GitRepository"
    name: "flux-system"
