apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dragonfly-operator
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./kubernetes/overlays/infrastructure/infra/applications/dragonfly-operator
  dependsOn: 
    - name: repositories-infra
    - name: external-secrets-config
  healthChecks:
    - kind: HelmRelease
      name: dragonfly-operator
      namespace: dragonfly-operator
      apiVersion: helm.toolkit.fluxcd.io/v2beta1
  prune: false
  sourceRef:
    kind: "GitRepository"
    name: "flux-system"
