---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets-config
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./kubernetes/overlays/infrastructure/infra/config/external-secrets
  dependsOn: 
    - name: external-secrets
  prune: true
  sourceRef:
    kind: "GitRepository"
    name: "flux-system"
