---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: longhorn
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./kubernetes/overlays/infrastructure/infra/applications/longhorn
  prune: true
  dependsOn: 
    - name: external-secrets-config
    - name: repositories-infra
  healthChecks:
    - kind: HelmRelease
      name: longhorn
      namespace: longhorn-system
      apiVersion: helm.toolkit.fluxcd.io/v2beta1
  sourceRef:
    kind: "GitRepository"
    name: "flux-system"
