---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: reloader
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./kubernetes/bases/reloader
  dependsOn: 
    - name: repositories-infra
  healthChecks:
    - kind: HelmRelease
      name: reloader
      namespace: reloader
      apiVersion: helm.toolkit.fluxcd.io/v2beta1
  prune: true
  sourceRef:
    kind: "GitRepository"
    name: "flux-system"
