---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: netbox-api-token-peppers
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: netbox-api-token-peppers
    creationPolicy: 'Owner'
    template:
      engineVersion: v2
      data:
        api-token-peppers.yaml: |
          API_TOKEN_PEPPERS:
            0: '{{ .pepper_0 }}'
  dataFrom:
  - extract:
      key: netbox/api-token-peppers
