---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: netbox-proxbox-config
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: netbox-proxbox-config
    creationPolicy: 'Owner'
    template:
      engineVersion: v2
      data:
        proxbox.yaml: |
          PLUGINS_CONFIG:
            proxbox:
              proxmox:
                domain: '{{ .domain }}'
                http_port: 8006
                user: '{{ .user }}'
                token:
                  name: '{{ .token_id }}'
                  value: '{{ .token_secret }}'
                ssl: true
                ssl_verify: false
              netbox:
                domain: 'netbox.example.com'
                http_port: 443
                token: '{{ .api_token }}'
                ssl: true
  dataFrom:
  - extract:
      key: netbox/proxbox/credentials
  - extract:
      key: netbox/superuser
