---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitlab-oauth-secret
spec:
  refreshInterval: "15s"
  secretStoreRef: 
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: gitlab-oauth-secret
    creationPolicy: 'Owner'
    template:
      engineVersion: v2
      data: 
        config: |
          name: "openid_connect"
          label: "Infra OIDC"
          args:
            name: "openid_connect"
            scope: ["openid","profile","email","groups"]
            response_type: "code"
            issuer: https://auth.example.com
            discovery: true
            client_auth_method: "basic"
            send_scope_to_token_endpoint: true
            pkce: true
            response_mode: "query"
            uid_field: "preferred_username"
            client_options:
              identifier: "gitlab"
              secret: "{{ .key }}"
              redirect_uri: "https://gitlab.example.com/users/auth/openid_connect/callback"
              gitlab:
                groups_attribute: "groups"
                required_groups: ["k8s-infra-gitlab-users"]
                admin_groups: ["k8s-infra-gitlab-admins"]
  dataFrom:
  - extract:
      key: authelia/clients/gitlab
