---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: object-store-config
spec:
  refreshInterval: "15s"
  secretStoreRef: 
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: object-store-config
    creationPolicy: 'Owner'
    template:
      engineVersion: v2
      data: 
        config: |
          provider: AWS
          region: us-east-1
          aws_access_key_id: {{ .key }} 
          aws_secret_access_key: {{ .secret }} 
          aws_signature_version: 4
          endpoint: https://s3.example.com
          host: s3.example.com
          path_style: true
  dataFrom:
  - extract:
      key: "s3"
