---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: registry-storage-config
spec:
  refreshInterval: "15s"
  secretStoreRef: 
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: registry-storage-config
    creationPolicy: 'Owner'
    template:
      engineVersion: v2
      data: 
        config: |
          s3:
            bucket: rke-gitlab-registry
            accesskey: {{ .key }}
            secretkey: {{ .secret }} 
            v4auth: true
            region: us-east-1
            regionendpoint: https://s3.example.com
            path_style: true
  dataFrom:
  - extract:
      key: "s3"
