apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager-discord
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: alertmanager-discord
    creationPolicy: 'Owner'
  data:
    - secretKey: webhook_url
      remoteRef:
        key: monitoring/discord
        property: webhook_url
