apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: app-secret
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: app-secret
    creationPolicy: 'Owner'
  data:
  - secretKey: APP_SECRET
    remoteRef:
      key: umami/credentials
      property: app_secret
  - secretKey: TWO_FACTOR_ENCRYPTION_KEY
    remoteRef:
      key: umami/credentials
      property: two_factor_encryption_key
