apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitlab-agent-token
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: gitlab-agent-token
    creationPolicy: Owner
  data:
  - secretKey: token
    remoteRef:
      key: gitlab/kas-agent
      property: token
