apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-pull-secret
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: harbor-pull-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {"auths":{"harbor.example.com}":{"username":"{{ .user }}","password":"{{ .secret }}","auth":"{{ printf "%s:%s" .user .secret | b64enc }}"}}}
  dataFrom:
  - extract:
      key: gitlab/agent/harbor
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homelab-registry-pull-secret
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: homelab-registry-pull-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {"auths":{"gitlab-registry.example.com/homelab":{"username":"token","password":"{{ .secret }}","auth":"{{ printf "%s:%s" "token" .secret | b64enc }}"}}}
  dataFrom:
  - extract:
      key: gitlab/agent/homelab-registry
