apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-admin-secret
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: harbor-admin-secret
    creationPolicy: 'Owner'
  data:
  - secretKey: admin_password
    remoteRef:
      key: harbor/credentials
      property: admin_password
