apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mealie
resources:
- ../../../../../bases/mealie
- postgres.yaml
- oidc-secret.yaml
- s3-secrets.yaml
components:
- ../../../../../components/ca-certs
patches:
- target:
    kind: HelmRelease
  path: mealie-patch.yaml