apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mealie
resources:
- ../../../../../bases/mealie
- postgres.yaml
- oidc-secret.yaml
- s3-secrets.yaml
components:
- ../../../../../components/ca-certs
- ../../../../../components/cnpg-barman-backup
patches:
- target:
    kind: HelmRelease
  path: mealie-patch.yaml
- target:
    kind: ScheduledBackup
    name: cnpg-nightly-backup
  patch: |
    - op: replace
      path: /spec/cluster/name
      value: mealie-db
- target:
    kind: RoleBinding
    name: cnpg-backup-s3-reader
  patch: |
    - op: replace
      path: /subjects/0/name
      value: mealie-db