apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oidc-secret
spec:
  refreshInterval: "15s"
  secretStoreRef: 
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: oidc-secret
    creationPolicy: 'Owner'
  data:
  - secretKey: key
    remoteRef: 
        key: authelia/clients/mealie
        property: key
