apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
spec:
  interval: 30m
  chart:
    spec:
      chart: immich
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: immich
        namespace: flux-system
      interval: 12h