apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ch-ui
resources:
- ../../../../../bases/ch-ui
- app-secret.yaml
patches:
- target:
    kind: HelmRelease
    name: ch-ui
  path: ch-ui-patch.yaml
