apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ipa-tsig-secret
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: ipa-tsig-secret
  data:
  - secretKey: rfc2136_tsig_secret
    remoteRef:
      key: external-dns/ipa-tsig
      property: secret