---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: netbox-oidc-config
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: netbox-oidc-config
    creationPolicy: 'Owner'
    template:
      engineVersion: v2
      data:
        oidc.yaml: |
          SOCIAL_AUTH_OIDC_ENDPOINT: 'https://auth.example.com'
          SOCIAL_AUTH_OIDC_KEY: 'netbox'
          SOCIAL_AUTH_OIDC_SECRET: '{{ .key }}'
          SOCIAL_AUTH_OIDC_SCOPE: ['openid', 'profile', 'email', 'groups']
          SOCIAL_AUTH_JSONFIELD_ENABLED: true
  dataFrom:
  - extract:
      key: authelia/clients/netbox
