---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: netbox-smtp
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: netbox-smtp
    creationPolicy: 'Owner'
  data:
  - secretKey: email-password
    remoteRef:
      key: netbox/smtp
      property: email-password
