apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oidc-secret
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: oidc-secret
  data:
  - secretKey: OAUTH_CLIENT_SECRET
    remoteRef:
      key: authelia/clients/karakeep
      property: key