apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  install:
    remediation:
      retries: -1
  upgrade: 
    remediation:
      retries: -1
  interval: 30m
  chart:
    spec:
      chart: external-secrets
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: flux-system
      interval: 12h