apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: dragonfly-operator
  namespace: flux-system
spec:
  interval: 24h
  url: oci://ghcr.io/dragonflydb/dragonfly-operator/helm
  type: oci
