apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: versitygw
  namespace: flux-system
spec:
  interval: 12h
  url: oci://ghcr.io/versity/versitygw/charts/versitygw
  ref:
    semver: ">=0.3.5"
