apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: keycloak
resources:
  - ../../../../../bases/keycloak
  - database/
  - secrets/
components:
  - ../../../../../components/ca-certs/
  - ../../../../../components/cnpg-barman-backup
patches:
  - target:
      kind: HelmRelease
      name: keycloak
    path: keycloak-patch.yaml
  - target:
      kind: ScheduledBackup
      name: cnpg-nightly-backup
    patch: |
      - op: replace
        path: /spec/cluster/name
        value: keycloak-db
  - target:
      kind: RoleBinding
      name: cnpg-backup-s3-reader
    patch: |
      - op: replace
        path: /subjects/0/name
        value: keycloak-db
