apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: secret-key
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: secret-key
    creationPolicy: 'Owner'
  data:
  - secretKey: secret_key
    remoteRef:
      key: paperless-ngx/secrets
      property: secret_key
