apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tika
spec:
  interval: 30m
  chart:
    spec:
      chart: tika
      version: "3.2.2"
      sourceRef:
        kind: HelmRepository
        name: tika
        namespace: flux-system
      interval: 12h
