apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-driver-nfs
  namespace: csi-driver-nfs
spec:
  install:
    remediation:
      retries: -1
  upgrade: 
    remediation:
      retries: -1
  interval: 30m
  chart:
    spec:
      chart: csi-driver-nfs
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: csi-driver-nfs
        namespace: flux-system
      interval: 12h
  values: 
    controller: 
      runOnControlPlane: true
      replicas: 1
    externalSnapshotter: 
      enabled: true