apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: maxmind-credentials
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: maxmind-credentials
  data:
  - secretKey: GEOIPUPDATE_ACCOUNT_ID
    remoteRef:
      key: maxmind/credentials
      property: account_id
  - secretKey: GEOIPUPDATE_LICENSE_KEY
    remoteRef:
      key: maxmind/credentials
      property: license_key
