apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: paperless-ngx
spec:
  interval: 30m
  chart:
    spec:
      chart: paperless-ngx
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: gabe565
        namespace: flux-system
      interval: 12h