---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openbao-oidc-config
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: openbao-oidc-config
    creationPolicy: 'Owner'
    template:
      engineVersion: v2
      data:
        oidc_client_id: 'openbao'
        oidc_client_secret: '{{ .key }}'
        oidc_discovery_url: 'https://auth.example.com'
  dataFrom:
  - extract:
      key: authelia/clients/openbao
