---
apiVersion: notification.toolkit.fluxcd.io/v1
kind: Receiver
metadata:
  name: from-authelia
  namespace: flux-system
spec:
  type: generic
  secretRef:
    name: receiver-token-from-authelia
  resources:
    - apiVersion: kustomize.toolkit.fluxcd.io/v1
      kind: Kustomization
      name: monitoring
      namespace: flux-system
    - apiVersion: kustomize.toolkit.fluxcd.io/v1
      kind: Kustomization
      name: headlamp
      namespace: flux-system
