---
apiVersion: notification.toolkit.fluxcd.io/v1
kind: Receiver
metadata:
  name: from-dragonfly-operator
  namespace: flux-system
spec:
  type: generic
  secretRef:
    name: receiver-token-from-dragonfly-operator
  resources:
    - apiVersion: kustomize.toolkit.fluxcd.io/v1
      kind: Kustomization
      name: authelia
      namespace: flux-system
