apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- from-external-secrets.yaml
- from-external-secrets-config.yaml
- from-longhorn.yaml
- from-cloudnative-pg.yaml
- from-cert-manager.yaml
- from-dragonfly-operator.yaml
- from-traefik.yaml
- from-authelia.yaml
