# yaml-language-server: $schema=https://json.schemastore.org/kustomization
namespace: dragonfly-operator
resources: 
  - ../../../../../bases/dragonfly-operator
patches: 
  - target: 
      kind: HelmRelease
    path: dragonfly-operator-patch.yaml
