apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
secretGenerator:
  - name: ipa-ca
    files: 
    - ca-certificates.crt
configMapGenerator:
  - name: ipa-ca
    files: 
    - ca-certificates.crt
generatorOptions:
  disableNameSuffixHash: true
