---
apiVersion: v1
kind: Secret
metadata:
  name: receiver-token-from-external-secrets
  namespace: flux-system
stringData:
  token: "92afb1fab647c5e1dcea1e7a8c94d82a9b0a7a5bf442c0bdd82c3ce344e39917"
---
apiVersion: v1
kind: Secret
metadata:
  name: receiver-token-from-external-secrets-config
  namespace: flux-system
stringData:
  token: "f3d1679a34cfd9f063b38581d3c72ad20984f16d0e6387b1119e61afe6aa71bb"
---
apiVersion: v1
kind: Secret
metadata:
  name: receiver-token-from-longhorn
  namespace: flux-system
stringData:
  token: "9d51743868a5b477e40586dec0c545090d93c231e149f857fec79fd88e0454c0"
---
apiVersion: v1
kind: Secret
metadata:
  name: receiver-token-from-cloudnative-pg
  namespace: flux-system
stringData:
  token: "1fc25bd46d491976f49b1acaacd689b4e6ea3ea29686290bcce8c9b3c0691e2e"
---
apiVersion: v1
kind: Secret
metadata:
  name: receiver-token-from-cert-manager
  namespace: flux-system
stringData:
  token: "338e8dc4ed7cb75a3388a38e2cb91c620948e3b268615f4d7acddc274998ff7b"
---
apiVersion: v1
kind: Secret
metadata:
  name: receiver-token-from-dragonfly-operator
  namespace: flux-system
stringData:
  token: "5cb07cf7d2e1fb8659c4047a86d7fa2ac759b9e56c6fafe4fb8ec54b77505bc4"
---
apiVersion: v1
kind: Secret
metadata:
  name: receiver-token-from-traefik
  namespace: flux-system
stringData:
  token: "2d9262b36e9d10ca5be55d6c1b74aa26b37bc8b2638775ac4647469614b5c936"
---
apiVersion: v1
kind: Secret
metadata:
  name: receiver-token-from-authelia
  namespace: flux-system
stringData:
  token: "f66540bf3d4f5d14a769b51430db2b1d39b0b6b566679b30c61da53a1ad7b446"
