---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cilium-leases-role
  namespace: kube-system
rules:
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
--- 
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cilium-leases-permissions
  namespace: kube-system
subjects:
- kind: ServiceAccount
  name: cilium
  namespace: kube-system
roleRef:
  kind: Role
  name: cilium-leases-role  
  apiGroup: rbac.authorization.k8s.io