apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 30m
  install:
    remediation:
      retries: -1
  upgrade: 
    remediation:
      retries: -1
  chart:
    spec:
      chart: cilium
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
      interval: 12h