apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: k8s-store-role
rules:
- apiGroups: [""]
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - authorization.k8s.io
  resources:
  - selfsubjectrulesreviews
  verbs:
  - create
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-store
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: k8s-store
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: k8s-store-role
subjects:
- kind: ServiceAccount
  name: k8s-store
