apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: k8s-store
spec:
  provider:
    kubernetes:
      remoteNamespace: default
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
      auth:
        serviceAccount:
          name: k8s-store