apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: guacamole
spec:
  interval: 15m
  chart:
    spec:
      chart: guacamole
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m