#SPDX-License-Identifier: MIT-0
---
# handlers file for install_frigate
- name: Restart networking
  ansible.builtin.systemd:
    name: networking
    state: restarted

- name: Restart Frigate
  ansible.builtin.command:
    cmd: "docker compose -f {{ install_frigate_config_path }}/docker-compose.yml restart"
  args:
    chdir: "{{ install_frigate_config_path }}"
  register: frigate_start_result
  changed_when: frigate_start_result.rc == 0
