apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: harbor
resources:
- ../../../../../bases/harbor
- ./database
- ./secrets
patches:
- target:
    kind: HelmRelease
    name: harbor
  path: harbor-patch.yaml
