apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kafka-ui-oidc
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: kafka-ui-oidc
    creationPolicy: 'Owner'
  data:
  # Authelia holds the argon2id hash of this same value under 'hash'.
  - secretKey: client-secret
    remoteRef:
      key: authelia/clients/kafka-ui
      property: key
