apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: versitygw
resources:
- ../../../../../bases/versitygw
- nfs-storage.yaml
- root-credentials-secret.yaml
patches:
- target:
    kind: HelmRelease
    name: versitygw
  path: versitygw-patch.yaml
