- name: Check if secrets engine exists
  ansible.builtin.command: "vault secrets list -detailed -format=json"
  register: vault_secrets_list
  changed_when: out.rc == 0
  failed_when: out.rc != 0 and out.rc != 2

- name: Enable KV secrets engine
  ansible.builtin.command: "vault secrets enable -plugin-version=2 -path={{ item.path }}/ kv"
  loop: "{{ vault_kv_secret_engines }}"
  when: not (item.path + "/" in ((vault_secrets_list.stdout | from_json).keys()|list))
  changed_when: out.rc == 0
  failed_when: out.rc != 0 and out.rc != 2
