apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: whoami
spec:
  interval: 30m
  chart:
    spec:
      chart: whoami
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: cowboysysop
        namespace: flux-system
      interval: 12h