apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dragonfly-operator
spec:
  interval: 30m
  install:
    remediation:
      retries: -1
  upgrade: 
    remediation:
      retries: -1
  chart:
    spec:
      chart: dragonfly-operator
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: dragonfly-operator
        namespace: flux-system
      interval: 12h
