apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gotify-credentials
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: gotify-credentials
    creationPolicy: Owner
  data:
    - secretKey: GOTIFY_DEFAULTUSER_NAME
      remoteRef:
        key: gotify/credentials
        property: username
    - secretKey: GOTIFY_DEFAULTUSER_PASS
      remoteRef:
        key: gotify/credentials
        property: password
