apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "https://vault01.infra.internal"
      path: "k8s-infra"
      version: "v2"
      caProvider:
        type: ConfigMap
        name: ipa-ca
        key: ca-certificates.crt
        namespace: external-secrets
      auth:
        # VaultLdap authenticates with Vault using the LDAP auth mechanism
        # https://www.vaultproject.io/docs/auth/ldap
        ldap:
          # Path where the LDAP authentication backend is mounted
          path: "ldap"
          # LDAP username
          username: "svc_k8s_infra_vault_access"
          secretRef:
            name: "vault-secret"
            key: "password"
            namespace: external-secrets
