apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gitlab
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./kubernetes/overlays/apps/infra/applications/gitlab
  healthChecks:
    - kind: HelmRelease
      name: gitlab
      namespace: gitlab
      apiVersion: helm.toolkit.fluxcd.io/v2beta1
  prune: true
  sourceRef:
    kind: "GitRepository"
    name: "flux-system"
