apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mealie
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./kubernetes/overlays/apps/infra/applications/mealie
  healthChecks:
    - kind: HelmRelease
      name: mealie
      namespace: mealie
      apiVersion: helm.toolkit.fluxcd.io/v2beta1
  prune: true
  sourceRef:
    kind: "GitRepository"
    name: "flux-system"
