apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headlamp
spec:
  chart:
    spec:
      version: "0.35.0"
  values:
    config:
      pluginsDir: /build/plugins
      oidc:
        externalSecret:
          enabled: true
          name: oidc-secret
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-issuer"
        nginx.ingress.kubernetes.io/auth-method: 'GET'
        nginx.ingress.kubernetes.io/auth-signin: "https://auth.example.com?rm=$request_method"
        nginx.ingress.kubernetes.io/auth-url: "http://authelia.authelia.svc.cluster.local/api/authz/auth-request"
      ingressClassName: nginx
      hosts:
        - host: headlamp.example.com
          paths:
            - path: /
              type: ImplementationSpecific
      tls:
        - secretName: headlamp-ingress-tls-cert
          hosts: 
            - headlamp.example.com
    initContainers:
      - command:
          - /bin/sh
          - -c
          - mkdir -p /build/plugins && cp -r /plugins/* /build/plugins/
        image: ghcr.io/headlamp-k8s/headlamp-plugin-flux:latest
        imagePullPolicy: Always
        name: headlamp-plugins
        volumeMounts:
          - mountPath: /build/plugins
            name: headlamp-plugins
    persistentVolumeClaim:
      accessModes:
        - ReadWriteOnce
      enabled: true
      size: 1Gi
    volumeMounts:
      - mountPath: /build/plugins
        name: headlamp-plugins
    volumes:
      - name: headlamp-plugins
        persistentVolumeClaim:
          claimName: headlamp