apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headlamp
spec:
  chart:
    spec:
      version: "0.42.0"
  values:
    config:
      watchPlugins: true
      oidc:
        clientID: kubelogin
        issuerURL: https://auth.0b.au
        usePKCE: true
        scopes: "profile,email,groups"
    pluginsManager:
      enabled: true
      configContent: |
        plugins:
          - name: headlamp_flux
            source: https://artifacthub.io/packages/headlamp/headlamp-plugins/headlamp_flux
          - name: headlamp_cert-manager
            source: https://artifacthub.io/packages/headlamp/headlamp-plugins/headlamp_cert-manager
    ingress:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.middlewares: traefik-authelia@kubernetescrd
      ingressClassName: traefik
      hosts:
        - host: headlamp.0b.au
          paths:
            - path: /
              type: ImplementationSpecific