apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: gitlab-db
  namespace: gitlab
spec:
  inheritedMetadata:
    labels:
      recurring-job-group.longhorn.io/default: disabled
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:18.4
  storage:
    size: 50Gi
  monitoring:
    enablePodMonitor: true
