variable "proxmox_api_url" {
    type = string
}

variable "proxmox_api_token_id" {
    type = string
}

variable "proxmox_api_token_secret" {
    type = string
    sensitive = true
}

source "proxmox-iso" "autogenerated_1" {
    proxmox_url = "${var.proxmox_api_url}"
    username = "${var.proxmox_api_token_id}"
    token = "${var.proxmox_api_token_secret}"
    insecure_skip_tls_verify = true

    boot_iso {
        type = "scsi"
        iso_file = "ISO:iso/Rocky-10.0-x86_64-minimal.iso"
        unmount = true
        iso_storage_pool = "ISO"
    }

    node = "hydrogen"
    vm_id = "901"
    vm_name = "rocky10"
    template_description = "Rocky 10 Image"

    cpu_type = "host"

    qemu_agent = true

    scsi_controller = "virtio-scsi-pci"

    disks {
        disk_size = "30G"
        format = "raw"
        storage_pool = "local-zfs"
        # storage_pool_type = "zfs"
        type = "virtio"
    }

    # VM CPU Settings
    cores = "2"

    # VM Memory Settings
    memory = "4096" 

    # VM Network Settings
    network_adapters {
        model = "virtio"
        bridge = "build"
        firewall = "false"
    } 
    
    boot_command = ["<up>e<enter><down><down><end> text inst.ks=http://{{ .HTTPIP }}:{{ .HTTPPort }}/inst.ks<f10><wait>"]
    boot_wait    = "10s"
    communicator            = "ssh"

    http_directory          = "${path.root}/http"

    ssh_username            = "cloud-user"
    ssh_private_key_file    = "~/.ssh/id_ed25519"

    ssh_timeout             = "30m"
    ssh_pty                 = true

    # VM Cloud-Init Settings
    cloud_init = true
    cloud_init_storage_pool = "local-zfs"
}

build {
    sources = ["source.proxmox-iso.autogenerated_1"]
  
    name = "proxmox-rl9"

    provisioner "ansible" {
      playbook_file = "./ansible/playbook.yaml"
      use_proxy = false
      extra_arguments = ["--vault-password-file=${path.root}/../../ansible/bw_vault_password.sh"]
    }

}