apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: encryption-key
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: encryption-key
  data:
  - secretKey: encryption_key
    remoteRef:
      key: authelia/encryption_key
      property: key
