apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ldap-bind-password
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: ldap-bind-password
  data:
  - secretKey: bind_password
    remoteRef:
      key: authelia/ldap
      property: password
