
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oidc-clients
spec:
  refreshInterval: 15s
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: oidc-clients
    template:
      engineVersion: v2
      templateFrom:
        - configMap:
            name: oidc-config
            items:
              - key: config.oidc.yaml
  data:
  - secretKey: config_jwks_key
    remoteRef:
      key: authelia/jwks_key
      property: key
  - secretKey: config_hmac_secret
    remoteRef:
      key: authelia/hmac
      property: key
  - secretKey: kubelogin_password_hash
    remoteRef:
      key: authelia/clients/kubelogin
      property: hash
  - secretKey: gitlab_password_hash
    remoteRef:
      key: authelia/clients/gitlab
      property: hash
  - secretKey: grafana_password_hash
    remoteRef:
      key: authelia/clients/grafana
      property: hash
  - secretKey: aka_password_hash
    remoteRef:
      key: authelia/clients/aka
      property: hash
  - secretKey: karakeep_password_hash
    remoteRef:
      key: authelia/clients/karakeep
      property: hash
  - secretKey: mealie_password_hash
    remoteRef:
      key: authelia/clients/mealie
      property: hash
  - secretKey: immich_password_hash
    remoteRef:
      key: authelia/clients/immich
      property: hash
  - secretKey: coder_password_hash
    remoteRef:
      key: authelia/clients/coder
      property: hash
  - secretKey: paperless_password_hash
    remoteRef:
      key: authelia/clients/paperless-ngx
      property: hash
  - secretKey: freshrss_password_hash
    remoteRef:
      key: authelia/clients/freshrss
      property: hash