apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pw-reset
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: pw-reset
  data:
  - secretKey: jwt
    remoteRef:
      key: authelia/pw_reset
      property: jwt
