apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: smtp-secret
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: smtp-secret
  data:
  - secretKey: secret
    remoteRef:
      key: authelia/smtp
      property: secret
