apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: couchdb-admin
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: couchdb-couchdb
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        adminUsername: "admin"
        adminPassword: "{{ .password }}"
        cookieAuthSecret: "{{ .cookie_secret }}"
        erlangCookie: "{{ .erlang_cookie }}"
  dataFrom:
  - extract:
      key: couchdb/credentials
