apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: couchdb
resources:
- ../../../../../bases/couchdb
- admin-secret.yaml
- cors-middleware.yaml
- ingressroute.yaml
patches:
- target:
    kind: HelmRelease
    name: couchdb
  path: couchdb-patch.yaml
