apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: config-secret
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: config-secret
  dataFrom:
  - extract:
      key: freshrss/config