apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: claude-secret
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: claude-secret
    creationPolicy: 'Owner'
  data:
  - secretKey: token
    remoteRef:
      key: claude/token
      property: token
