apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: proxmox-secret
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: proxmox-secret
    creationPolicy: 'Owner'
  data:
  - secretKey: token
    remoteRef:
      key: coder/proxmox
      property: token
  - secretKey: id
    remoteRef:
      key: coder/proxmox
      property: id
