apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: harbor-db
spec:
  inheritedMetadata:
    labels:
      recurring-job-group.longhorn.io/default: disabled
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:16.6
  storage:
    size: 10Gi
    storageClass: longhorn
  monitoring:
    enablePodMonitor: true
