apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cnpg-backup-s3
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: cnpg-backup-s3
  data:
  - secretKey: ACCESS_KEY_ID
    remoteRef:
      key: s3
      property: key
  - secretKey: ACCESS_SECRET_KEY
    remoteRef:
      key: s3
      property: secret
