apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: aka
resources:
- ../../../../../bases/aka
- postgres.yaml
- oidc-secret.yaml
components:
- ../../../../../components/ca-certs
patches:
- target:
    kind: HelmRelease
  path: aka-patch.yaml
