apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: renovate-operator
spec:
  interval: 30m
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  chart:
    spec:
      chart: renovate-operator
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: mogenius
        namespace: flux-system
      interval: 12h
