apiVersion: apps/v1
kind: Deployment
metadata:
  name: speedtest-exporter
  labels:
    app: speedtest-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: speedtest-exporter
  template:
    metadata:
      labels:
        app: speedtest-exporter
    spec:
      containers:
        - name: speedtest-exporter
          image: ghcr.io/heathcliff26/speedtest-exporter:latest
          ports:
            - name: metrics
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 128Mi
