apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pve-tag-proxy
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 12h
  values: 
    controllers:
      pve-tag-proxy:
        containers:
          app:
            image:
              repository: ghcr.io/ashmantis1/proxmox-tag-proxy
              tag: main
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
            resources:
              limits:
                memory: 2000Mi
              requests:
                cpu: 10m
                memory: 250Mi
    service:
      app:
        controller: pve-tag-proxy
        ports:
          http:
            port: 5000
    defaultPodOptions:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 1000
        runAsUser: 1000