apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-configmap-loki
  labels:
     grafana_datasource: "1"
  # annotations:
  #     k8s-sidecar-target-directory = "/tmp/dashboards/[FODLER]"
data:
  loki.yaml: |-
    apiVersion: 1
    datasources:
        # <string, required> Name of the VictoriaLogs datasource
        # displayed in Grafana panels and queries.
      - name: Loki
        # <string, required> Sets the data source type.
        type: loki
        access: proxy
        url: http://loki-gateway.monitoring.svc.cluster.local:80
        isDefault: false