apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dashy
resources:
- ../../../../../bases/dashy
components:
- ../../../../../components/ca-certs
patches:
- target:
    kind: HelmRelease
  path: dashy-patch.yaml