apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dashy
spec:
  interval: 30m
  chart:
    spec:
      chart: dashy
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: vyrtualsynthese
        namespace: flux-system
      interval: 12h
