apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
spec:
  install:
    remediation:
      retries: -1
  upgrade: 
    remediation:
      retries: -1
  interval: 30m
  chart:
    spec:
      chart: longhorn
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
      interval: 12h
