---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs
provisioner: nfs.csi.k8s.io
parameters:
  server: REDACTED_IP
  share: /mnt/storage
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate