apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: open-webui
resources:
- ../../../../../bases/open-webui
- oidc-secret.yaml
components:
- ../../../../../components/ca-certs
patches:
- target:
    kind: HelmRelease
  path: open-webui-patch.yaml
