namespace: ingress-nginx
resources:
  - ../../../../../bases/ingress-nginx
patches: 
  - target: 
      kind: HelmRelease
    path: ./ingress-nginx-patch.yaml
  - target:
      kind: Namespace
    patch: |
      - op: add
        path: /metadata/labels
        value:
          role: ingress-controller
