---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: notify-from-external-secrets
  namespace: flux-system
spec:
  type: generic
  address: http://notification-controller.flux-system.svc.cluster.local:9292/hook/6635f001fae0c060a018e85d20ef853bec1238a09a61ef336221bcb1396579d2
