---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: notify-from-external-secrets-config
  namespace: flux-system
spec:
  type: generic
  address: http://notification-controller.flux-system.svc.cluster.local:9292/hook/271b0ee51a33c50d80146aa797810b53f1997c6a8313c9637057e4dcc4e4539e
